### PR TITLE
(WIP) PCB files

### PR DESCRIPTION
**Pull request by ibnuda**
currently i'm working on the pcb files as i've stated in the r/ergomechboards.

- [x] create schematic
- [x] create kicad's pcb file
  - [x] placed footprints to their rightful places according to the switch plate (`arch_40_plate.dxf`).
  - [x] create cutout
  - [x] route the pcb

### CODE REVIEW

**Comment by jacekplonowski** [comment]
Awesome work, thank you ibnuda !!

**Comment by ibnuda** [comment]
@jacekplonowski, it is finished.

**Comment by jacekplonowski** [comment]
Sweet, looks really nice, one question though: does the PCB have holes to accommodate for the standoffs passing through the case? 
ksnip_20191111-225345

**Comment by ibnuda** [comment]
Oh, right. I will fix it ASAP.

**Comment by jacekplonowski** [comment]
@ibnuda no problem, I'll be back on my computer in about 7 hrs or so, no rush. I'll merge it sometime around then or whenever works for you

**Comment by ibnuda** [comment]
i have put the holes to match the plate file.

**Comment by jacekplonowski** [comment]
Hey @ibnuda I just noticed something in KiCad that might pose an issue with the current case design:
I believe this part of the pcb needs to be changed on both sides, otherwise it will not fit inside the case, I would try to do it myself, but I'm afraid I will end up breaking the gerber files since I am not experienced in KiCad.

pcb

**Comment by ibnuda** [comment]
oh, that's easy problem. in a minute.

**Pull request merged**
